'use client'

import type { ReactNode } from 'react'
import { Printer } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { formatDateTime } from '@/lib/format'

/** A printable receipt page. "Print" also lets people save it as a PDF from the browser. */
export default function ReceiptShell({ title, number, issuedAt, to, children }: {
  title: string
  number: string
  issuedAt: string
  to: { name: string | null; email: string }
  children: ReactNode
}) {
  return (
    <div className="mx-auto max-w-2xl px-4 py-8 print:max-w-none print:p-0">
      <div className="mb-4 flex justify-end print:hidden">
        <Button variant="outline" onClick={() => window.print()}><Printer className="mr-2 h-4 w-4" aria-hidden />Print or save as PDF</Button>
      </div>
      <article className="space-y-6 rounded-lg border bg-card p-6 print:border-0 print:p-0">
        <header className="flex flex-wrap items-start justify-between gap-4 border-b pb-4">
          <div>
            <p className="text-xl font-bold text-primary">TutorLink</p>
            <p className="text-xs text-muted-foreground">Home tutoring, Nigeria</p>
          </div>
          <div className="text-right text-sm">
            <p className="text-lg font-semibold">{title}</p>
            <p>Receipt no. <span className="font-mono">{number}</span></p>
            <p className="text-muted-foreground">{formatDateTime(issuedAt)}</p>
          </div>
        </header>
        <div className="text-sm">
          <p className="text-muted-foreground">Issued to</p>
          <p className="font-medium">{to.name ?? to.email}</p>
          <p className="text-muted-foreground">{to.email}</p>
        </div>
        {children}
        <footer className="border-t pt-4 text-xs text-muted-foreground">
          This receipt was generated by TutorLink. Keep it for your records.
        </footer>
      </article>
    </div>
  )
}
