"""Private file storage: Cloudflare R2 when configured, otherwise a local folder (development only).

Files are never public. Callers hand out short-lived signed URLs from `url()`.
"""

import hashlib
import hmac
import mimetypes
import time
from functools import lru_cache
from pathlib import Path
from urllib.parse import quote

from app.core.config import settings


def r2_configured() -> bool:
    return all([settings.R2_ACCOUNT_ID, settings.R2_ACCESS_KEY_ID, settings.R2_SECRET_ACCESS_KEY, settings.R2_BUCKET])


@lru_cache
def _r2_client():
    import boto3  # imported lazily: only needed when R2 is configured

    return boto3.client(
        "s3",
        endpoint_url=f"https://{settings.R2_ACCOUNT_ID}.r2.cloudflarestorage.com",
        aws_access_key_id=settings.R2_ACCESS_KEY_ID,
        aws_secret_access_key=settings.R2_SECRET_ACCESS_KEY,
        region_name="auto",
    )


def _local_path(key: str) -> Path:
    root = Path(settings.LOCAL_STORAGE_DIR).resolve()
    path = (root / key).resolve()
    if root not in path.parents:  # keys are generated by us, but never let one escape the folder
        raise ValueError("Invalid storage key")
    return path


def save(key: str, data: bytes, content_type: str) -> None:
    if r2_configured():
        _r2_client().put_object(Bucket=settings.R2_BUCKET, Key=key, Body=data, ContentType=content_type)
        return
    path = _local_path(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def delete(key: str) -> None:
    if r2_configured():
        _r2_client().delete_object(Bucket=settings.R2_BUCKET, Key=key)
        return
    _local_path(key).unlink(missing_ok=True)


def local_signature(key: str, expires: int) -> str:
    return hmac.new(settings.SECRET_KEY.encode(), f"{key}:{expires}".encode(), hashlib.sha256).hexdigest()


def url(key: str, expires_in: int = 900) -> str:
    """A URL that lets whoever holds it read the file for `expires_in` seconds."""
    if r2_configured():
        return _r2_client().generate_presigned_url(
            "get_object", Params={"Bucket": settings.R2_BUCKET, "Key": key}, ExpiresIn=expires_in,
        )
    expires = int(time.time()) + expires_in
    return f"{settings.BASE_URL}/v1/files/{quote(key)}?expires={expires}&sig={local_signature(key, expires)}"


def read_local(key: str) -> tuple[bytes, str] | None:
    """Local-storage file bytes and content type, for the development file route."""
    path = _local_path(key)
    if not path.is_file():
        return None
    return path.read_bytes(), mimetypes.guess_type(path.name)[0] or "application/octet-stream"
