"""Private file storage: Cloudflare R2 when configured, otherwise a local folder (development only).

Files are never public. Callers hand out short-lived signed URLs from `url()`.
"""

import hashlib
import hmac
import mimetypes
import time
from functools import lru_cache
from pathlib import Path
from urllib.parse import quote

from app.core.config import settings

# Same answer on every OS (Windows reads these from the registry otherwise).
for _type, _ext in (("video/mp4", ".mp4"), ("video/webm", ".webm"), ("video/quicktime", ".mov")):
    mimetypes.add_type(_type, _ext)


def r2_configured() -> bool:
    return all([settings.R2_ACCOUNT_ID, settings.R2_ACCESS_KEY_ID, settings.R2_SECRET_ACCESS_KEY, settings.R2_BUCKET])


@lru_cache
def _r2_client():
    import boto3  # imported lazily: only needed when R2 is configured

    return boto3.client(
        "s3",
        endpoint_url=f"https://{settings.R2_ACCOUNT_ID}.r2.cloudflarestorage.com",
        aws_access_key_id=settings.R2_ACCESS_KEY_ID,
        aws_secret_access_key=settings.R2_SECRET_ACCESS_KEY,
        region_name="auto",
    )


def _local_path(key: str) -> Path:
    root = Path(settings.LOCAL_STORAGE_DIR).resolve()
    path = (root / key).resolve()
    if root not in path.parents:  # keys are generated by us, but never let one escape the folder
        raise ValueError("Invalid storage key")
    return path


def save(key: str, data: bytes, content_type: str) -> None:
    if r2_configured():
        _r2_client().put_object(Bucket=settings.R2_BUCKET, Key=key, Body=data, ContentType=content_type)
        return
    path = _local_path(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def delete(key: str) -> None:
    if r2_configured():
        _r2_client().delete_object(Bucket=settings.R2_BUCKET, Key=key)
        return
    _local_path(key).unlink(missing_ok=True)


def local_signature(key: str, expires: int) -> str:
    return hmac.new(settings.SECRET_KEY.encode(), f"{key}:{expires}".encode(), hashlib.sha256).hexdigest()


def url(key: str, expires_in: int = 900) -> str:
    """A URL that lets whoever holds it read the file for `expires_in` seconds."""
    if r2_configured():
        return _r2_client().generate_presigned_url(
            "get_object", Params={"Bucket": settings.R2_BUCKET, "Key": key}, ExpiresIn=expires_in,
        )
    expires = int(time.time()) + expires_in
    return f"{settings.BASE_URL}/v1/files/{quote(key)}?expires={expires}&sig={local_signature(key, expires)}"


def read_local(key: str) -> tuple[bytes, str] | None:
    """Local-storage file bytes and content type, for the development file route."""
    path = _local_path(key)
    if not path.is_file():
        return None
    return path.read_bytes(), mimetypes.guess_type(path.name)[0] or "application/octet-stream"


def upload_url(key: str, content_type: str, size: int, expires_in: int = 900) -> str:
    """A URL the browser PUTs the file to directly, so large files never pass through the API. The
    content type and exact size are part of the signature: a different file is refused."""
    if r2_configured():
        return _r2_client().generate_presigned_url(
            "put_object",
            Params={"Bucket": settings.R2_BUCKET, "Key": key, "ContentType": content_type, "ContentLength": size},
            ExpiresIn=expires_in,
        )
    expires = int(time.time()) + expires_in
    sig = local_signature(upload_signing_key(key, content_type, size), expires)
    return (f"{settings.BASE_URL}/v1/files/{quote(key)}?expires={expires}&size={size}"
            f"&type={quote(content_type, safe='')}&sig={sig}")


def upload_signing_key(key: str, content_type: str, size: int) -> str:
    return f"put:{key}:{content_type}:{size}"


def head(key: str) -> tuple[int, str] | None:
    """(size in bytes, content type) of a stored file, or None if there is no such file."""
    if r2_configured():
        from botocore.exceptions import ClientError

        try:
            found = _r2_client().head_object(Bucket=settings.R2_BUCKET, Key=key)
        except ClientError:
            return None
        return int(found["ContentLength"]), found.get("ContentType") or "application/octet-stream"
    path = _local_path(key)
    if not path.is_file():
        return None
    return path.stat().st_size, mimetypes.guess_type(path.name)[0] or "application/octet-stream"


def local_file(key: str) -> Path:
    """Where a local-storage file lives, for the development upload route."""
    path = _local_path(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    return path
